# Generated by Django 6.0.2 on 2026-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100)),
                ('test_case', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('passed', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
